# A headless service to create DNS records
apiVersion:                          v1
kind:                                Service
metadata:
  name:                              flume
  namespace:                         yarn-cluster
  labels:
    component:                       flume
spec:
  ports:
  - name:                            agent-source-1
    port:                            41414
    protocol:                        TCP
  - name:                            monitoring
    port:                            34343
    protocol:                        TCP
  # *.flume.yarn-cluster.svc.cluster.local
  type:                              NodePort
  selector:
    component:                       flume
---
apiVersion:                          apps/v1beta1
kind:                                StatefulSet
metadata:
  name:                              flume
spec:
  serviceName:                       flume
  template:
    metadata:
      labels:
        component:                   flume
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name:                        flume
        imagePullPolicy:             Always
        image:                       yswtrue/hadoop:2.7.6
        command:
           - "/bin/bash"
           - "/tmp/hadoop-config/bootstrap.sh"
        resources:
          requests:
            memory:                  "1024Mi"
            cpu:                     "100m"
          limits:
            memory:                  "2048Mi"
            cpu:                     "4000m"
        env:
          - name:                    MY_CPU_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName:       flume
                resource:            limits.cpu
                divisor:             1
          - name:                    MY_MEM_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName:       flume
                resource:            limits.memory
                divisor:             1M
        volumeMounts:
          - name:                    hadoop-config
            mountPath:               /tmp/hadoop-config
          - name:                    data
            mountPath:               /data
      volumes:
        - name:                      hadoop-config
          configMap:
            name:                    hadoop-config
  volumeClaimTemplates:
  - metadata:
      name:                          data
    spec:
      accessModes:                   [ "ReadWriteOnce" ]
      storageClassName:              "nfs"
      resources:
        requests:
          storage:                   200Gi
